# Generated by Django 5.2.4 on 2025-08-01 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_id', models.CharField(max_length=50, unique=True, verbose_name='ID Aéronef')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('aircraft_type', models.CharField(blank=True, max_length=50, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aéronef',
                'verbose_name_plural': 'Aéronefs',
                'ordering': ['aircraft_id'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'analyse")),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminée'), ('failed', 'Échouée')], default='pending', max_length=20)),
                ('files_processed', models.IntegerField(default=0)),
                ('violations_found', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Session d'analyse",
                'verbose_name_plural': "Sessions d'analyse",
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RedZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la zone')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('polygon_coordinates', models.JSONField(verbose_name='Coordonnées du polygone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Zone active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zone rouge',
                'verbose_name_plural': 'Zones rouges',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name="Horodatage de l'alerte")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('alert_type', models.CharField(choices=[('intrusion', 'Intrusion détectée'), ('proximity', 'Proximité'), ('manual', 'Alerte manuelle')], default='intrusion', max_length=50, verbose_name="Type d'alerte")),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traitée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('red_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.redzone')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_at_alert', models.JSONField(verbose_name="Position à l'instant de l'alerte")),
                ('distance_to_zone', models.FloatField(verbose_name='Distance à la zone (m)')),
                ('is_inside_zone', models.BooleanField(verbose_name="À l'intérieur de la zone")),
                ('entry_time', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'entrée")),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de sortie')),
                ('duration_in_zone', models.DurationField(blank=True, null=True, verbose_name='Durée dans la zone')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='core.aircraft')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='core.alert')),
            ],
            options={
                'verbose_name': 'Violation',
                'verbose_name_plural': 'Violations',
                'ordering': ['-alert__timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Horodatage')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='Altitude (m)')),
                ('speed', models.FloatField(blank=True, null=True, verbose_name='Vitesse (km/h)')),
                ('heading', models.FloatField(blank=True, null=True, verbose_name='Cap (degrés)')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_data', to='core.aircraft')),
            ],
            options={
                'verbose_name': 'Donnée de vol',
                'verbose_name_plural': 'Données de vol',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='core_flight_timesta_7cfa47_idx'), models.Index(fields=['latitude', 'longitude'], name='core_flight_latitud_e294d1_idx')],
            },
        ),
    ]
