# Generated by Django 5.2.4 on 2025-08-01 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'import")),
                ('file_type', models.CharField(choices=[('flight_data', 'Données de vol'), ('red_zones', 'Zones rouges'), ('alerts', 'Alertes')], max_length=20, verbose_name='Type de fichier')),
                ('file_path', models.FileField(upload_to='imports/', verbose_name='Fichier')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_errors', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Session d'importation",
                'verbose_name_plural': "Sessions d'importation",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_column', models.CharField(max_length=100, verbose_name='Colonne source')),
                ('target_field', models.CharField(max_length=100, verbose_name='Champ cible')),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=200, verbose_name='Valeur par défaut')),
                ('import_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='imports.importsession')),
            ],
            options={
                'verbose_name': 'Mapping de colonne',
                'verbose_name_plural': 'Mappings de colonnes',
                'unique_together': {('import_session', 'target_field')},
            },
        ),
    ]
