# Generated by Django 5.2.4 on 2025-08-01 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du rapport')),
                ('report_type', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('html', 'HTML')], default='pdf', max_length=10, verbose_name='Type de rapport')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Fichier du rapport')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('generating', 'En cours de génération'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('analysis_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.analysissession', verbose_name="Session d'analyse")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('related_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.alert', verbose_name='Alerte liée')),
                ('related_violations', models.ManyToManyField(blank=True, to='core.violation', verbose_name='Violations liées')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-created_at'],
            },
        ),
    ]
